# Generated by Django 5.0.3 on 2024-03-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_new_my_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='my_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
